### PR TITLE
adapt bench_poll for split of poll and register

### PR DESCRIPTION
**Pull request by frehberg**
Hi Carl, the fix looks a bit ugly. Any reason there is no Events::len() method?

### CODE REVIEW

**Comment by carllerche** [comment]
You can always use [`Iterator::count`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.count).

`len` is deprecated as there is no way for Mio to get the number of polled events in constant time. This is because Mio reserves the right to internally make registrations which will be stored in the events struct.

**Comment by frehberg** [comment]
using `Iterator::count` looks much better, thanks for the hint

**Comment by frehberg** [comment]
Ready for merge! (?)

**Comment by frehberg** [comment]
Please let me know if anything is missing.

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
