### PR TITLE
Modify UdpSocket::connect() to take SocketAddr by ref (#667)

### PR DESCRIPTION
**Pull request by bobbo**
Change argument for `UdpSocket::connect()` to take `&SocketAddr`. This is more consistent with other `UdpSocket` methods, plus the `TcpSocket::connect()` method. Closes issue #667.

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @bobbo! This looks good to me :+1:

**Comment by carllerche** [comment]
This is unfortunately a breaking change :(

So, this can't be merged until an 0.7 release is planned. *or* `UdpSocket::connect` is deprecated in favor of `UdpSocket::connect2` (and it is switched back or 0.7).

**Comment by carllerche** [comment]
If you are up for it, could you rebase this against the `v0.7.x` branch? I am using that as staging for v0.7.x

**Comment by bobbo** [comment]
Hi @carllerche, I've rebased on top of `v0.7.x` and changed PR target branch.

**Pull request merged**
