### PR TITLE
Remove the FreeBSD build from Travis

### PR DESCRIPTION
**Pull request by asomers**
It uses BuildBot now
Issue #738

### CODE REVIEW

**Comment by asomers** [comment]
Buildbot swears that it updated the status for this issue, but it's not showing up.  Perhaps I don't have permission to post status updates?

**Comment by carllerche** [comment]
@asomers ah, weird I missed this PR.

I can look in a bit.

**Comment by asomers** [comment]
There are two problems ATM:
1) BuildBot isn't able to post status updates, probably because @asomers isn't a collaborator, though I can't find any GitHub documentation that says I need to be.
2) The FreeBSD tests are failing due to https://github.com/rust-lang/rust/issues/45038 .  I'm leaning toward disabling doc tests on FreeBSD to workaround that issue.

**Comment by asomers** [comment]
The problem with the doc tests seems to be fixed in Rust 1.22.0.  I ran 2214 times in a row with no problems.  It was also fixed in FreeBSD's patched rust a long time ago, but the patches seem to have finally percolated upstream.

**Comment by carllerche** [comment]
I added you as a collaborator, so you should be able to get things posting back.

**Comment by carllerche** [comment]
Let me know if there is anything else that I have to do.

**Comment by kpp** [comment]
@asomers Hello. Is there any progress on the issue?

**Comment by asomers** [comment]
Everything works 99% of the time, but occasionally the mio tests cause my VM to lock up.  It's rare enough that I haven't been able to debug it, but common enough that it's a problem.  I'll try enabling it again with a newer rustc and see if the problem persists.

**Comment by asomers** [comment]
rebased

**Comment by carllerche** [comment]
@asomers looks like it is hanging on CI in this build?

I am trying to rebuild...

**Comment by asomers** [comment]
It's not hanging; it's failing.  And it's failing because it needs https://github.com/carllerche/mio/pull/829 to be merged first.  And I _think_ I've fixed the hangs in my VM just by adding more RAM.  But we'll probably have to run for a full month to be certain.

**Comment by carllerche** [comment]
Ah I missed that PR. I will get that one merged.

**Pull request merged**
