### PR TITLE
Introduce option for steady ticks.

### PR DESCRIPTION
**Pull request by dpc**
This test current hangs, attesting issue #316.

### CODE REVIEW

**Comment by dpc** [comment]
I don't know why Windows test fails. Please help. :)

**Comment by dpc** [comment]
Ping. :)

**Comment by carllerche** [comment]
Sorry for the delay. I actually pulled this in as part of a larger refactor I was working on that hasn't landed yet. This will be in soon though.

**Comment by carllerche** [comment]
Ah sorry I thought this was a different PR that. I don't think that I'm going to pull this. It would be fairly simple to get this functionality as Mio is currently. You would just have to is implement [your own `run` fn](https://github.com/carllerche/mio/blob/master/src/event_loop.rs#L254-L263) with the functionality that you want. It's really short right now.

**Comment by dpc** [comment]
So you're saying I should call run_once() in loop in my own function? I guess that's OK for me. Thanks.

**Comment by carllerche** [comment]
Exactly. It also has the advantage of you being able to add further logic around blocking besides steady tick.

**Pull request closed without merging**
