### PR TITLE
Support broadcast on UDP sockets

### PR DESCRIPTION
**Pull request by vhbit**
Requires https://github.com/carllerche/nix-rust/pull/86 to land.

### CODE REVIEW

**Comment by carllerche** [comment]
I'm actually in the process of getting rid of mio's UDP socket impl in favor of the one in std (which already has broadcast), so this won't be needed anymore.

**Comment by carllerche** [comment]
Ok, I pushed UDP support update. It now uses std::net types: https://github.com/carllerche/mio/commit/ec77c8fcc84d7c2fc3bb9b4a5e9bbc03badf732a

I'm definitely interested in feedback though since I personally haven't used UDP all that much. Closing this for now, but as always feel free to open new tickets.

**Comment by vhbit** [comment]
I've tried to migrate, but was immediately blocked by missing support of `set_reuse_port` and `set_reuse_addr` in `std::net` udp socket, so for now I have no feedback either as have to stick with old version.

**Comment by rrichardson** [comment]
That seems like pretty good feedback.

**Comment by carllerche** [comment]
@vhbit You should still be able to access these functions. They are implemented on `Socket` which is implemented on `std::net::UdpSocket` (https://github.com/carllerche/mio/blob/master/src/net/udp.rs#L20)

Does that work for you?

**Comment by vhbit** [comment]
The problem is that should be used before bind, which is impossible in
std::net as it combines socket creation and binding.

**Comment by carllerche** [comment]
Ok, I should have a fix today

**Comment by carllerche** [comment]
This should be handled in 29c5e32fe96e70b762e65fe7d59a605d367d9597

`udp::v4() -> NonBlock<UdpSocket>`

**Comment by vhbit** [comment]
@carllerche thanks!

**Comment by vhbit** [comment]
btw, have you discussed with the core team a way to create `std::net` sockets from existing fd without transmuting?

**Comment by carllerche** [comment]
@vhbit I have, it should be coming pre 1.0

**Pull request closed without merging**
