### PR TITLE
add CI for aarch64-linux-android

### PR DESCRIPTION
**Pull request by chshawkn**
@MortimerGoro Moved CI integration to a separate PR as you asked.

### CODE REVIEW

**Comment by MortimerGoro** [comment]
Thanks!

**Comment by chshawkn** [comment]
@carllerche 

CI  for aarch64-linux-android is done. 

But I don't known why test_custom_evented::* tests runs on aarch64-linux-android but not on arm-linux-androideabi.

logs:
* [aarch64-linux-android](https://travis-ci.org/carllerche/mio/jobs/231497439)
* [arm-linux-androideabi](https://travis-ci.org/carllerche/mio/jobs/231483960)

The test_custom_evented test is time consuming and may be terminated by travis-ci sometimes.

**Comment by carllerche** [comment]
Well, it seems like I pushed to this branch instead of mine on Mio o_O How does github even work?

**Comment by MortimerGoro** [comment]
@MortimerGoro Can you please publish the fix to crates.io?

**Comment by carllerche** [comment]
done

**Pull request merged**
