### PR TITLE
Implement Drop for kqueue Selector

### LINKED ISSUE #372: kqueue: not close when dropped
Hi, I notice that kqueue won't be close when dropped, which will cause our bench tests failed due to "too many open files". 

I also notice that epoll is closed when dropped. So why kqueue is different?

### PR DESCRIPTION
**Pull request by hjr3**
Should fix issues where mio encounters a "Too many open files" error
when using kqueue.

Fixes #372

### CODE REVIEW

**Comment by BusyJay** [comment]
Is there something wrong with the checks? Why the first check still not complete after 11 days?

**Comment by hjr3** [comment]
I will re-push and see if that fixes.

**Comment by carllerche** [comment]
👍 I will try to merge this. Thanks.

**Comment by carllerche** [comment]
Thanks! Merged here: d14b04cff8045a3791cb93e36b9c0c2f3cb1e0c8

**Comment by BusyJay** [comment]
Will there be a minor release for it?

**Comment by carllerche** [comment]
I merged this into master... I could try to back port it.

**Pull request closed without merging**
