### PR TITLE
Add shutdown function

### PR DESCRIPTION
**Pull request by hoxnox**
Provided by nix::socket::shutdown.

### CODE REVIEW

**Comment by carllerche** [comment]
Looks good. One minor nit, I would redefine the `Shutdown` struct in mio. I think it would go best in [net/mod.rs](https://github.com/carllerche/mio/blob/master/src/net/mod.rs). Generated docs will be better and one day, there will be windows support which won't have access to nix :smile:

**Comment by hoxnox** [comment]
Yah, i thought about it. It would be better to define Shutdown in mio.

**Comment by carllerche** [comment]
Cool, I'll keep an eye open for the change :+1:

**Comment by hoxnox** [comment]
I redefined Shutdown in net::tcp. Not in net because TcpStream, which defines shutdown function, is in net::tcp.

**Comment by carllerche** [comment]
Good call! Looks good to me.

**Pull request merged**
