### PR TITLE
Remove uses of the deprecated tcp module.

### PR DESCRIPTION
**Pull request by ahmedcharles**
#655

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! For backwards compatibility though could this defer the actual deletion until later? For now I think we mainly just want to remove it's usage, not the deprecated pieces themselves yet

**Comment by ahmedcharles** [comment]
Sure.

**Comment by ahmedcharles** [comment]
I decided to split it into a few PR's to make reviews easier.

**Comment by alexcrichton** [comment]
Thanks so much for doing this! Looks like the Windows tests are failing though?

**Comment by ahmedcharles** [comment]
I don't see any correlation between the failures and any changes I made. I'll probably push PR's for each commit so I can see which one causes the failure and perhaps that will bring more insight.

**Comment by ahmedcharles** [comment]
I'll just have a PR for each commit, at least for ones without merge conflicts.

**Comment by ahmedcharles** [comment]
Rerunning the tests, since there was a docker failure.

**Pull request merged**
