### PR TITLE
use nix from crates.io

### PR DESCRIPTION
**Pull request by KalitaAlexey**
It is blocked by https://github.com/nix-rust/nix/issues/286

### CODE REVIEW

**Comment by kamalmarhubi** [comment]
Update: blocked by https://github.com/nix-rust/nix/issues/269

Should get sorted this week!

**Comment by kamalmarhubi** [comment]
We have a [0.5.0](https://crates.io/crates/nix/0.5.0)!

**Comment by petevine** [comment]
Is this PR supposed to be equivalent to:

https://github.com/thkaw/mio/commit/8add138f57b3c4e520a1054498d84bf999da2e8a ?

[Parity](https://github.com/ethcore/parity/issues/266) on ARM is currently blocked by the nix/mio combo even though manually overriding dependencies works.

**Comment by kamalmarhubi** [comment]
@petevine could you go into a bit more detail? is there anything we can do on the nix side to help?

**Comment by petevine** [comment]
Nix `0.5` solves the ARM compilation issues but the currently available version of mio needs that patch to work with latest nix. My request is about patching the 0.5.x branch of mio.

**Comment by posborne** [comment]
The next version of Nix should also have fixes for mips/android as well and we are working on improving testing for different platforms.  Once that infrastructure is in place, I'll see about making that infrastructure available in some way to other projects like mio (the need to test on each platform tends to decrease the further the crate is from the OS/metal. so that might not be necessary for mio).

**Comment by seanmonstar** [comment]
Could we get this merged and `mio@0.5.1` released with it?

**Comment by carllerche** [comment]
Yes.... I know I know.. I've been slow!

**Comment by carllerche** [comment]
Thanks for this. I ended up having to do a bunch of work to rebase it, but I pulled this in and released mio 0.5.1

**Comment by petevine** [comment]
Thanks @carllerche, ARM can rest easy now ;)

**Pull request closed without merging**
