### PR TITLE
Fix Clippy warnings

### PR DESCRIPTION
**Pull request by mcarton**
Nothing really bad here.

### CODE REVIEW

**Comment by mcarton** [comment]
Oh, why do you test against *nightly* and *1.3.0*? The current release is *1.6.0* (and you can just ask travis to test against *stable*, it will pick the last release).

**Comment by carllerche** [comment]
Hi @mcarton, we test explicitly against Rust 1.3 because that is the oldest version of Rust officially supported by Mio. When we decide to stop supporting a version of Rust, we change it in travis :)

**Comment by mcarton** [comment]
@carllerche ok, I fixed the thing that was not compatible with *1.3*, but you should still consider testing on both *1.3* and *stable* in that case :smile:.

**Comment by carllerche** [comment]
Thanks! Merged: 7d4778f226e3f2479e802ccb0934e1e8db3b31a1

**Pull request closed without merging**
