### PR TITLE
Added some examples fo mio::net::UdpSocket.

### PR DESCRIPTION
**Pull request by lanedraex**
Some rustdoc examples: (#665)

Includes examples for: UdpSocket, bind, local_addr, send_to, recv_from, set_broadcast, broadcast.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR!

I think including a full example for the struct level docs is probably good, however, for each individual function, would it be possible to reduce down the example to focus on the function as question? This should make it easier to see the relevant bits. Ideally, none of the fn level examples would include a full event loop.

**Comment by lanedraex** [comment]
Hey, should the examples hide the event loop with `#` or should I simply "fake" calls to the functions like:

```rust
# Ok(())
socket.send_to(&buffer, &addr);
```

Or something else entirely?

**Comment by carllerche** [comment]
@lanedraex sticking with fake calls is fine. You can use the `no_run` annotation I think it is.

**Comment by carllerche** [comment]
@lanedraex Thanks, these examples look great.

**Comment by lanedraex** [comment]
I'll add examples to the other methods.

Also, just noticed that I made a typo in the pull request title, sorry.

**Pull request merged**
