### PR TITLE
convert try!() to ?

### PR DESCRIPTION
**Pull request by guanqun**
No functional changes.

The change follows the Rust coding guidelines.

### CODE REVIEW

**Comment by rom1v** [comment]
The `?` operator requires rust 1.13, so the `.travis.yml` file would need to be updated:
https://github.com/carllerche/mio/blob/a5415ba319e1bef09980f972caf4ffc9bf92d5b4/.travis.yml#L20-L27

**Comment by guanqun** [comment]
It says:

```
    # 1.9.0 is the oldest supported version of Rust. This value should NOT be
    # changed without prior discussion.
    #
    # This build also deploys docs
```

So I assume it's OK to upgrade to 1.13?

**Comment by guanqun** [comment]
ping.

**Comment by carllerche** [comment]
Yeah, we can update to 1.13.

**Comment by guanqun** [comment]
Thank you @carllerche In the last commit, I updated it to 1.13

**Comment by carllerche** [comment]
I rebased, waiting for CI to pass.

**Comment by guanqun** [comment]
hmmm.

The xcode build fails with:

```
The command "CARGO_TARGET_DIR=`pwd` sh ci/run-ios.sh $TARGET" exited with 255.
before_cache
0.26s$ chmod -R a+r $HOME/.cargo
cache.2
store build cache
0.01s
14.05schange detected (content changed, file is created, or file is deleted):
/Users/travis/.cargo/registry/cache/github.com-1ecc6299db9ec823/libc-0.2.28.crate
/Users/travis/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/FETCH_HEAD
/Users/travis/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/logs/refs/remotes/origin/master
/Users/travis/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects/pack/pack-20ea364f52bb096393f0d1ba7250af0b698f4f00.idx
/Users/travis/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/objects/pack/pack-20ea364f52bb096393f0d1ba7250af0b698f4f00.pack
/Users/travis/.cargo/registry/index/github.com-1ecc6299db9ec823/.git/refs/remotes/origin/master
/Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.28/.cargo-ok
/Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.28/.gitignore
/Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.28/.travis.yml
/Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.28/Cargo.toml
/Users/travis/.cargo/registry/src/git
...
changes detected, packing new archive
.
uploading archive
Done. Your build exited with 1.
/Users/travis/.travis/job_stages: line 166: shell_session_update: command not found
```

It doesn't look like a code issue, probably some config issue, I'll check if I understand the travis setup...

**Pull request merged**
