### PR TITLE
Apply a lowercase to all the mio names.

### PR DESCRIPTION
**Pull request by dethoter**
Fix for #679.

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for contrib 👍 

I think that "Mio" should be treated as a proper noun at this point (capitalizing the first letter).

Capitalization has changed over time due to what the "Mio" name meant. It has converged to being a proper noun.

**Comment by KodrAus** [comment]
Maybe we should update the references in the README too. There are a few different ways the lib is referred to in there:

- `mio`
- mio
- MIO

**Comment by carllerche** [comment]
Updating the README would be good too, however, `mio` refers to the crate literal (what is imported).

**Comment by dethoter** [comment]
Closing this PR since changes are senseless.

**Comment by KodrAus** [comment]
@dethoter I don't think these changes are senseless, and am glad you got stuck in and made them! It's subtle but significant to have consistent naming.

**Comment by carllerche** [comment]
Yeah, I don't think it is senseless either, it is pretty subtle :)

**Comment by dethoter** [comment]
Apologize, I haven't been clear enough. @carllerche decided that 
>"Mio" should be treated as a proper noun

Here I changed `Mio` to `mio` that's incorrect according to accepted decision. So *exactly this PR* is senseless. I'll open a new one to update README.

**Pull request closed without merging**
