### PR TITLE
bump bytes to 0.4

### PR DESCRIPTION
**Pull request by ignatenkobrain**

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. It looks like CI doesn't like this?

**Comment by carllerche** [comment]
Sorry, accidentally closed.

**Comment by ignatenkobrain** [comment]
Let me take look at it..

**Comment by ignatenkobrain** [comment]
@carllerche I'm totally lost with changes in `bytes`. I've fixed some errors, but I don't know how to replace RingBuf and SliceBuf...

**Comment by ignatenkobrain** [comment]
@carllerche if you could port it yourself, would be very helpful for me since I need this in order to package for Fedora.

**Comment by carllerche** [comment]
@ignatenkobrain I'm unsure if there will be an effort to update bytes in mio 0.6 as most of (if not all of) the usage of `bytes` will be removed in 0.7 I think?

**Pull request closed without merging**
