### PR TITLE
Remove deprecated functionality

### PR DESCRIPTION
**Pull request by ahmedcharles**
This isn't intended to be merged immediately. It's just easy to create this PR at the same time as removing uses of the functionality.

### CODE REVIEW

**Comment by carllerche** [comment]
Let me know when I should look at this / merge it :)

**Comment by ahmedcharles** [comment]
I'll rebase later/over the weekend. Are you ready to remove all the deprecated features?

**Comment by carllerche** [comment]
Ah sorry, I thought this was for tests... no the deprecated items in the lib need to stay until the next version bump.

**Comment by carllerche** [comment]
Sorry for the delay. I think that I may have done some of this work already. Could you check the `v0.7.x` branch and see if this PR is still needed or if there is more deprecated code to merge?

Thanks!

**Comment by ahmedcharles** [comment]
#804

**Pull request closed without merging**
