### PR TITLE
Abort process if refcount overflows

### PR DESCRIPTION
**Pull request by stjepang**
This resolves a TODO left in the comments.

### CODE REVIEW

**Comment by stjepang** [comment]
Travis fails due to an unrelated problem: associated constants are not supported by Rust 1.18.0.

**Comment by carllerche** [comment]
Thanks so much for this and sorry for the delay. CI has not been a good state. We got CI working on master! would you be able to pull in the latest master?

**Comment by stjepang** [comment]
CI is passing now :)

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
